CREATE DATABASE IF NOT EXISTS CYBER_INSURANCE;

CREATE SCHEMA IF NOT EXISTS CYBER_INSURANCE.RAW;
CREATE SCHEMA IF NOT EXISTS CYBER_INSURANCE.STAGING;
CREATE SCHEMA IF NOT EXISTS CYBER_INSURANCE.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS CYBER_INSURANCE.ANALYTICS;

CREATE TABLE IF NOT EXISTS CYBER_INSURANCE.RAW.SECURITY_EVENTS (
    event_id VARCHAR,
    customer_id VARCHAR,
    event_type VARCHAR,
    severity VARCHAR,
    risk_score NUMBER,
    event_timestamp TIMESTAMP_NTZ,
    updated_at TIMESTAMP_NTZ,
    ingestion_timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TABLE IF NOT EXISTS CYBER_INSURANCE.RAW.CUSTOMERS (
    customer_id VARCHAR,
    plan_tier VARCHAR,
    risk_segment VARCHAR,
    updated_at TIMESTAMP_NTZ,
    ingestion_timestamp TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP()
);